### PR TITLE
Support subdirectories

### PR DESCRIPTION
**Pull request by the-ress**

### CODE REVIEW

**Comment by jetfir3** [comment]
this PR worked perfectly for unpacking files with subdirectories (e.g., language-related resources) but now conflicts with the new change to "pyxamstore".

**Comment by the-ress** [comment]
Note: I ported the change to the current code. I haven't actually tried running it so please let me know if it needs any more changes.

**Comment by jakev** [comment]
Do you mind sharing the name/URL of the APK you're looking at here? I'm curious what the structure looks like before I merge this, as I'm making a bunch of changes to account for architecture specific assemblies. I might as well handle your use case too!

**Comment by the-ress** [comment]
@jakev it's this apk: https://www.apkmonk.com/app/de.miele.infocontrol/

It has lots of localized resources in subfolders:
```
...
0xbe1c9b47  0xdc8c92bfa428a168  000      0354      sl/Miele.Libraries.Behaviors.resources
0x6da7af55  0x35c693b71bedcdad  000      0355      sk/Miele.Libraries.Behaviors.resources
0x726470a3  0x60ae3565b082d274  000      0356      zh-Hans/Miele.Libraries.Behaviors.resources
0x4fe4428a  0x1e68d386251dd5b3  000      0357      zh-Hant/Miele.Libraries.Behaviors.resources
0xcad02630  0x8902b51aeff75120  000      0358      de-AT/Miele.Libraries.Behaviors.resources
0xbf0c0aa8  0xdfbe3d2e2cbf1b7c  000      0359      pl/Miele.Libraries.Behaviors.resources
0x27d9f669  0x88d69591b155f882  000      0360      sv/Miele.Libraries.Behaviors.resources
0xd42f1a30  0xbdace532ce354db9  000      0361      nn/Miele.Libraries.Behaviors.resources
0x60e765af  0x3964bbf556b169ba  000      0362      da/Miele.Libraries.Behaviors.resources
0x74515c15  0x8cbbd54ebecfeab4  000      0363      ja/Miele.Libraries.Behaviors.resources
...
```

**Comment by jakev** [comment]
Thanks! I have a series of commits that should work here but I'll have to test this in the next few days. Will report back.

**Comment by jakev** [comment]
@the-ress do you mind testing with the latest commits? It should work now. If it works for you, I'll close this pull request as the code was pretty heavily refactored. :)

Thank you for the help!

**Comment by jakev** [comment]
I'm going to close this, as it should be resolved. Thanks for reporting!

**Pull request closed without merging**
